---
kind: pipeline
name: verify
steps:
  - name: credentials
    image: robertstettner/drone-npm-auth
    token:
      from_secret: NPM_TOKEN

  - name: install
    image: node:10.15.3
    commands:
      - npm ci
    depends_on:
      - credentials

  - name: verify
    image: node:10.15.3
    commands:
      - npm run lint
      - npm run test
    depends_on:
      - install

  - name: build
    image: node:10.15.3
    commands:
      - npm run build
    depends_on:
      - verify

  - name: deploy
    image: jmccann/drone-terraform:1
    plan: false
    depends_on:
      - build
