---
kind: pipeline
name: pr
steps:
  - name: install
    image: node:10.15.3
    commands:
      - npm ci

  - name: lint
    image: node:10.15.3
    commands:
      - npm run lint
    depends_on:
      - install

  - name: test
    image: node:10.15.3
    commands:
      - npm run test
    depends_on:
      - install

trigger:
  event: pull_request

---
kind: pipeline
name: master
steps:
  - name: install
    image: node:10.15.3
    commands:
      - npm ci

  - name: lint
    image: node:10.15.3
    commands:
      - npm run lint
    depends_on:
      - install

  - name: test
    image: node:10.15.3
    commands:
      - npm run test
    depends_on:
      - install

  - name: build
    image: node:10.15.3
    commands:
      - npm run build
    depends_on:
      - install

  - name: deploy
    image: jmccann/drone-terraform:1
    plan: false
    depends_on:
      - build
      - lint
      - test

trigger:
  branch: master
  event: push
